name: Appium Java Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18' # Specify the Java version (e.g., 11, 17)
          distribution: 'zulu' # Use Temurin (Adoptium) as the JDK distribution

      # Set up Node.js (required for Appium)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      # Install Appium globally
      - name: Install Appium
        run: npm install -g appium@next
        continue-on-error: true

      # Install android driver for appium
      - name: Install Android driver  
        run: appium driver install uiautomator2
        continue-on-error: true
   
      # Install ios driver for appium
      - name: Install iOS driver 
        run: appium driver install xcuitest
        continue-on-error: true
      
      # Run Maven tests (assuming you're using Maven)
      - name: Run Maven tests
        run: mvn clean install

      # Optional: Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: test-results
          path: target/surefire-reports/ # Path to test results (adjust as needed)
